In [7]:
import numpy as n
arr=n.array([1,2,45,12,23,3,4,45,34,121,3,3,45])
temp=n.where(arr==3)
print(f"The locations of 4 in the array are: {temp}")

The locations of 4 in the array are: (array([ 5, 10, 11], dtype=int64),)


In [8]:
temp1=n.where(arr%2==0)
print(f"The locations of even nums in the array are: {temp1}")

The locations of even nums in the array are: (array([1, 3, 6, 8], dtype=int64),)


In [10]:
x=n.sort(arr)
print(x)

[  1   2   3   3   3   4  12  23  34  45  45  45 121]


In [12]:
y=n.searchsorted(x,6)
print(y)

6


In [13]:
z=n.array([[1,4,5,2],[12,4,5,2]])
print(n.sort(z))

[[ 1  2  4  5]
 [ 2  4  5 12]]


In [14]:
x1=[True,False,True,False,True,False,True,False,True,False,True,False,True]
new=x[x1]
print(new)

[  1   3   3  12  34  45 121]


In [25]:
arr21=n.array([1,2,3,4])
x_2=arr21>3
print(x_2)
new1=arr21[x_2]
print(new1)

[False False False  True]
[4]
