In [2]:
import numpy as n
a=n.array([[1,2,3,4],[5,6,7,8]])
print(a)

[[1 2 3 4]
 [5 6 7 8]]


In [3]:
b=n.zeros((3,5))
print(b)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [5]:
c=n.full((3,5),2)
print(c)

[[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]


In [10]:
d=n.random.random((5,3))
print(d)

[[0.10197936 0.82262893 0.66465933]
 [0.53245615 0.45743243 0.91207587]
 [0.2202847  0.0698336  0.55002991]
 [0.37735849 0.8402918  0.77616907]
 [0.28511182 0.77581189 0.83366439]]


In [11]:
e=n.arange(0,10,2)
print(e)

[0 2 4 6 8]


In [14]:
e=d.reshape(3,5)
print(e)

[[0.10197936 0.82262893 0.66465933 0.53245615 0.45743243]
 [0.91207587 0.2202847  0.0698336  0.55002991 0.37735849]
 [0.8402918  0.77616907 0.28511182 0.77581189 0.83366439]]


In [16]:
f=e.flatten()
print(f)

[0.10197936 0.82262893 0.66465933 0.53245615 0.45743243 0.91207587
 0.2202847  0.0698336  0.55002991 0.37735849 0.8402918  0.77616907
 0.28511182 0.77581189 0.83366439]


In [18]:
print(e.ndim)

2


In [19]:
  print(e.shape)

(3, 5)


In [20]:
print(e.dtype)

float64


In [21]:
print(e.astype('i'))

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
