In [1]:
import numpy as n
arr1=n.array([1,23,23,12,15])
arr2=n.array([13,12,34,67,56])
print(f"Original:\n{arr1}\n{arr2}\n")



Original:
[ 1 23 23 12 15]
[13 12 34 67 56]



In [2]:
print(f"Vector Addition:\n{arr1+arr2}")

Vector Addition:
[14 35 57 79 71]


In [3]:
print(f"Vector subtraction:\n{arr1-arr2}")

Vector subtraction:
[-12  11 -11 -55 -41]


In [4]:
print(f"Vector multiplication:\n{arr1*arr2}")

Vector multiplication:
[ 13 276 782 804 840]


In [5]:
print(f"Vector division:\n{arr2/arr1}")

Vector division:
[13.          0.52173913  1.47826087  5.58333333  3.73333333]


In [6]:
print(f"Vector dot product :\n{arr1.dot(arr2)}")

Vector dot product :
2715


In [7]:
sclr=5
print(f"Scalar Multiplication : \n{sclr*arr1}")

Scalar Multiplication : 
[  5 115 115  60  75]


In [8]:
def func(x,y):
    if x>y:
        return x-y
    else:
        return x+y
arr1=[1,2,3]
arr2=[4,5,6]
vec_func=n.vectorize(func)
print(vec_func(arr1,arr2))

[5 7 9]
