In [2]:
import numpy as n
arr=n.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print("The original array: \n",arr)

The original array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [6]:
print("Every other row:\n",arr[0:3:2])

Every other row:
 [[ 1  2  3  4]
 [ 9 10 11 12]]


In [7]:
print("Slicing:\n",arr[1:4:])

Slicing:
 [[ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [8]:
print("Indexing:\n",arr[:,1:4])

Indexing:
 [[ 2  3  4]
 [ 6  7  8]
 [10 11 12]
 [14 15 16]]


In [2]:
import numpy as n
arr=n.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
temp=arr[[0,1,2,3],[0,1,2,3]]
print(temp)

[ 1  6 11 16]


In [4]:
cond= arr>3
temp=arr[cond]
print(temp)

[ 4  5  6  7  8  9 10 11 12 13 14 15 16]


In [9]:
arr1=n.array([1,2,3,4,5])
arr2=n.array([5,6,7,8,9])
arr3=n.concatenate((arr1,arr2))
print(arr3)

[1 2 3 4 5 5 6 7 8 9]


In [10]:
arr4=n.hstack((arr1,arr2))
print(arr4)

[1 2 3 4 5 5 6 7 8 9]


In [11]:
arr4=n.vstack((arr1,arr2))
print(arr4)

[[1 2 3 4 5]
 [5 6 7 8 9]]


In [13]:
arr5=n.dstack((arr1,arr2))
print(arr5)

[[[1 5]
  [2 6]
  [3 7]
  [4 8]
  [5 9]]]


In [14]:
arr3=n.array([12,23,554,76,78])
arr6=n.dstack((arr1,arr2,arr3))
print(arr6)

[[[  1   5  12]
  [  2   6  23]
  [  3   7 554]
  [  4   8  76]
  [  5   9  78]]]


In [16]:
arr7=n.array_split(arr3,5)
print(arr7)

[array([12]), array([23]), array([554]), array([76]), array([78])]


In [17]:
print(f"\n{arr7[0]}\n{arr7[1]}\n{arr7[2]}")


[12]
[23]
[554]
